Dynamic User Setup and Cross-Platform Compatibility
Significant enhancements have been made to the asdf role,
introducing dynamic user setup and improved macOS compatibility.
The package management role has been simplified, and various roles have
been integrated into the workstation playbook. Molecule testing has
been expanded, providing comprehensive coverage for the updated roles
and playbooks. This release marks a major step forward in the project's
evolution, focusing on cross-platform support and user-centric configurations.

- Workstation Playbook - Added `workstation.yml` playbook with roles for zsh setup and asdf.
- Molecule Testing - Introduced Molecule configurations for the workstation playbook, including Docker platforms (Ubuntu and Red Hat) and a converge playbook importing `attack-box.yml`.
- Inventory Files - Created inventory files for both main and Molecule setups, defining localhost as a local connection.
- New inventory and molecule test setup for workstation playbook.
- Dynamic setting of shell profiles based on OS in asdf role.
- Checking for existence of .zshrc before creating new file in zsh_setup role.
- Introduced 'get_enriched_users.yml' task for fetching home directories in asdf role.
- Enhanced setup with dynamic user-specific paths and permissions in asdf role.
- Created 'package_individual_setup.yml' in asdf role for more granular package handling.
- Enhanced asdf role with user-specific setup scripts.
- Logging configuration enhancements in the logging role.
- Molecule testing configurations for `attack-box` playbook.
- Package management improvements for different distributions.
- User setup and zsh setup roles in `attack-box.yml`.

- Package Management Role - Updated `package_management` role to skip package installation on Darwin systems.
- Updated molecule github action to support new playbook directory structure.
- Enhanced asdf role for macOS and Linux compatibility.
- Updated `zsh_setup` role for better path handling and simplification.
- Simplified setup_asdf_env.sh script in asdf role.
- Modified the `home_path` variable in asdf role's defaults/main.yml.
- Updated tasks in asdf role's main.yml and package_individual_setup.yml.
- Refactored zsh_setup role for macOS and root user path compatibility.
- Updated `zsh_setup_users` and `asdf_users` variables for dynamic user handling.
- Streamlined `zsh_setup` and `asdf` roles for improved macOS compatibility.
- Simplified package management role with unified tasks for Debian and RedHat.
- Updated asdf role to remove OS-specific tasks and focus on user-based configuration.

- Removed old files in preparation for later refactoring.
- Windows Support for asdf role - Removed from `roles/asdf/README.md`.
- Deprecated vnc_zsh role and associated files in favor of streamlined setup.
- Removed Windows support in asdf role's documentation.

diff --git a/roles/asdf/tasks/package_individual_setup.yml b/roles/asdf/tasks/package_individual_setup.yml
--- a/roles/asdf/tasks/package_individual_setup.yml
+++ b/roles/asdf/tasks/package_individual_setup.yml
@@ -2,48 +2,47 @@
 - name: Get all plugins for each user
   ansible.builtin.shell:
     cmd: |
-      . /usr/local/bin/setup_asdf_env "{{ user.username }}"
+      set -o pipefail
+      . /usr/local/bin/setup_asdf_env "{{ item.home_path }}"
       asdf plugin list
-    executable: "{{ user.shell }}"
+    executable: "{{ item.shell }}"
   register: asdf_plugins
   changed_when: false
   become: true
-  become_user: "{{ user.username }}"
-  loop: "{{ asdf_users }}"
-  loop_control:
-    loop_var: user
-  when: user.username != 'root'
+  become_user: "{{ item.username }}"
 
 - name: Install asdf plugins for each user
   ansible.builtin.shell:
     cmd: |
       set -o pipefail
-      . /usr/local/bin/setup_asdf_env "{{ user_plugin.0.username }}"
-      if ! asdf plugin list | grep -q "{{ user_plugin.1.name }}"; then
-        asdf plugin add "{{ user_plugin.1.name }}"
+      . /usr/local/bin/setup_asdf_env "{{ item.home_path }}"
+      {% for plugin in item.plugins %}
+      if ! asdf plugin list | grep -q "{{ plugin.name }}"; then
+        asdf plugin add "{{ plugin.name }}"
       fi
-    executable: "{{ user_plugin.0.shell }}"
+      {% endfor %}
+    executable: "{{ item.shell }}"
   become: true
-  become_user: "{{ user_plugin.0.username }}"
-  loop: "{{ query('subelements', asdf_users, 'plugins', {'skip_missing': true}) }}"
-  loop_control:
-    loop_var: user_plugin
-  when: user_plugin.1.name is defined
+  become_user: "{{ item.username }}"
   changed_when: false
 
 - name: Install specific version of asdf plugins for each user
   ansible.builtin.shell:
     cmd: |
       set -o pipefail
-      . /usr/local/bin/setup_asdf_env "{{ user_plugin.0.username }}"
-      if ! asdf list "{{ user_plugin.1.name }}" | grep -q "{{ user_plugin.1.version }}"; then
-        asdf install "{{ user_plugin.1.name }}" "{{ user_plugin.1.version }}"
+      . /usr/local/bin/setup_asdf_env "{{ item.home_path }}"
+      {% for plugin in item.plugins %}
+      asdf install "{{ plugin.name }}" "{{ plugin.version }}"
+      if [ "{{ plugin.scope }}" = "global" ]; then
+        asdf global "{{ plugin.name }}" "{{ plugin.version }}"
+      elif [ "{{ plugin.scope }}" = "local" ]; then
+        asdf local "{{ plugin.name }}" "{{ plugin.version }}"
+      else
+        echo "Invalid scope: {{ plugin.scope }}"
+        exit 1
       fi
-    executable: "{{ user_plugin.0.shell }}"
+      {% endfor %}
+    executable: "{{ item.shell }}"
   become: true
-  become_user: "{{ user_plugin.0.username }}"
-  loop: "{{ query('subelements', asdf_users, 'plugins', {'skip_missing': true}) }}"
-  loop_control:
-    loop_var: user_plugin
-  when: user_plugin.1.name is defined and user_plugin.1.version is defined
+  become_user: "{{ item.username }}"
   changed_when: false
