Debugging renovate error

diff --git a/.github/workflows/renovate.yaml b/.github/workflows/renovate.yaml
--- a/.github/workflows/renovate.yaml
+++ b/.github/workflows/renovate.yaml
@@ -66,14 +66,15 @@ jobs:
       - name: Delete old dashboard
         run: |
           ISSUE_NUMBER=$(gh issue list -S 'Renovate Dashboard 🤖' --json number -q '.[0].number')
+          echo "Issue number fetched: $ISSUE_NUMBER"
           if [ "$ISSUE_NUMBER" != "null" ] && [ -n "$ISSUE_NUMBER" ]; then
-            gh issue close "$ISSUE_NUMBER"
+            gh issue close "$ISSUE_NUMBER" || echo "Failed to close issue."
           else
             echo "No issue found to close."
           fi
         env:
           GITHUB_TOKEN: "${{ steps.app-token.outputs.token }}"
-
+        
       - name: Renovate
         uses: renovatebot/github-action@b93d7e432be4d7ad29452a9a058aa130220e8819 # v39.2.2
         with:
